version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: facial-backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend/recognition.db:/app/recognition.db
    restart: always
    env_file:
      - ./backend/.env
